[package]
name = "trie"
version = "0.1.0"
edition = "2021"

[lib]
name = "trie"

[dependencies]
ptree = "0.4.0"
rand = "0.8.5"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
parity-wordlist = "1.3.1"

[[bench]]
name = "bench"
harness = false
